create buttons
anastasiia-avdeeva/Vesna-website pull request #19
Opened 2024-11-14 11:43 UTC by dianniii

Создала общие классы для классических кнопок, стили для них

2024-11-14 13:32 UTC, KamDiaV commented on assets/styles/_buttons.scss
> +    font-size: 20px;
Создам еще один миксин со шрифтом для кнопки этой, потом можно будет через @include добавить, чтобы однотипно было

2024-11-14 13:37 UTC, KamDiaV commented on assets/styles/_buttons.scss
> +    font-size: 20px;
@mixin button-free-consultation {
  @include h1;
  font-size: $font-size-button-free-consultation;
}

добавила миксин

2024-11-14 13:38 UTC, anastasiia-avdeeva requested changes
Как мне кажется стоит вынестив отдельный класс button все повторяющиеся свойства:
width:240px
height:60px
border: none
bcakground-color: $white;
color: $black
@include h5
для этого класса сделать ховер любой
А потом переопределить свойства которые надо изменить в отдельных классах и добавить новые если есть. То есть появляется базовая кнопка, а к ней уже другие классы с изменениями. Таким образом мы сокращаем код и убираем повторы по максимуму. И возможно, стоит называть модификаторы не по блоку а по тому что они меняют типа делаю кнопку уже или меняют цвет

2024-11-14 14:20 UTC, DaryaZhuravleva approved these changes

2024-11-16 10:19 UTC, DaryaZhuravleva approved these changes

2024-11-16 19:11 UTC, KamDiaV commented on assets/styles/_buttons.scss
> +    @include button-free-consultation;
поменять на новое название миксина @include button-transparent;

2024-11-16 19:12 UTC, KamDiaV approved these changes

2024-11-16 22:44 UTC, DaryaZhuravleva approved these changes

2024-11-18 08:08 UTC, anastasiia-avdeeva approved these changes

2024-11-18 08:08 UTC, merged