Footer
anastasiia-avdeeva/Vesna-website pull request #23
Opened 2024-11-16 11:07 UTC by dianniii

cоздала футер, и стили для него

2024-11-18 12:58 UTC, DaryaZhuravleva submitted a review, later dismissed

2024-11-18 21:53 UTC, anastasiia-avdeeva requested changes

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +    height: auto;
height: auto можно убрать, тк это значение стоит по умолчанию

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +        height: auto;
height: auto значение по умолчанию

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +    width: 100%;
width у блочных элементов - значение по умолчанию

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +            width: 100%;
ты ставишь боковые отступы сколько то пикселей и потом пишешь ширину 100%, это будет гарантировать что блок вместе с отступами будет занимать больше 100%. Это ошибка, которая приведет к переполнению footer, в котором лежит контейнер

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +            height: auto;
автоматическое значение

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +    width: 100%;
width у блочных элементов 100%  по умолчанию

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on assets/styles/_footer.scss
> +        font-size: 20px;
Для всех значений размеров шрифтов используем переменные

2024-11-18 21:53 UTC, anastasiia-avdeeva commented on portfolio.html
> +                <div class="footer__tim">
не очень понимаю название класса

2024-11-24 10:29 UTC, anastasiia-avdeeva submitted a review, later dismissed

2024-11-24 10:36 UTC, anastasiia-avdeeva approved these changes

2024-11-24 10:36 UTC, merged