Write _base.scss
anastasiia-avdeeva/Vesna-website pull request #4
Opened 2024-11-12 15:33 UTC by KamDiaV

2024-11-12 15:55 UTC, anastasiia-avdeeva requested changes
See comments in the code

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  height: 100%;
I am not sure that we need this rule.

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  min-width: 100%;
Could you please explain why we need this?

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +image {
Wouldn't it potentially create problems when we use img tag to insert icons?

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  padding: 0;
this is already applied by the rule for *

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  margin: 0;
See prev comment

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  margin-top: 0;
this is already in force through the rule for *

2024-11-12 15:55 UTC, anastasiia-avdeeva commented on assets/styles/_base.scss
> +  font-weight: normal;
Not sure why we need it

2024-11-12 16:44 UTC, DaryaZhuravleva approved these changes

2024-11-13 10:03 UTC, dianniii approved these changes

2024-11-13 13:50 UTC, anastasiia-avdeeva approved these changes

2024-11-13 13:50 UTC, merged